project:
  type: website

website:
  title: "Prasaath Sastha"
  open-graph: true
  google-analytics: "G-JRCX5DKQ7P"
  favicon: me.png
  navbar:
    logo: me.png
    pinned: true
    right: 
      - href: cv.qmd
        text: 🧑Curriculum Vittae
      - text: Projects
        menu:
        - href: publications.qmd
          text: 📑 Publications
        - href: https://prasaath-sastha.github.io/MSc-Project/
          text: 📚 MSc. Project
      - href: grades.qmd
        text: 💯 Grades
      - icon: github
        text: Github
        href: https://github.com/prasaath-sastha
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/prasaathsastha/
drafts:
      - href: blogindex.qmd
        text: My Blog
drafts-mode: unlinked

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false

editor: visual

