---
title: "Grades"
---

# MSc. Drug Discovery and Toxicology

University of Hertfordshire

| Module | Credits | Grade | GPA |
|------------------|------------------|------------------|------------------|
| Molecular Cell Biology and Immunology | 30 | 77 | 4.25 |
| Translational Medical Science | 30 | 79 | 4.25 |
| Molecular Medicine | 30 | 81 | 4.5 |
| Contemporary topics in Drug Discovery and Toxicology | 30 | 78 | 4.25 |
| [Research Project with Research Methodology](https://prasaath-sastha.github.io/MSc-Project/ "link to project site") | 60 | 84 | 4.5 |

# Doctor of Pharmacy

Vinayaka Mission's College of Pharmacy, Vinayaka Mission's Research Foundation

**Overall - 85%**

| Module | Score | Out of |
|------------------------|------------------------|------------------------|
| **Year I - 87.1%** |  |  |
| Human Anatomy and Physiology | 174 | 200 |
| Pharmaceutics | 156 | 200 |
| Medicinal Biochemistry | 191 | 200 |
| Pharmaceutical Organic Chemistry | 175 | 200 |
| Pharmaceutical Inorganic Chemistry | 175 | 200 |
| **Year II - 81.8%** |  |  |
| Pathophysiology | 70 | 100 |
| Pharmaceutical Microbiology | 166 | 200 |
| Pharmacognosy and Phyto Pharmaceuticals | 176 | 200 |
| Pharmacology-I | 159 | 200 |
| Community Pharmacy | 79 | 100 |
| Pharmacotherapeutics-I | 183 | 200 |
| **Year III - 81%** |  |  |
| Pharmacology-II | 173 | 200 |
| Pharmaceutical Analysis | 158 | 200 |
| Pharmacotherapeutics-II | 165 | 200 |
| Pharmaceutical Jurisprudence | 68 | 100 |
| Medicinal Chemistry | 180 | 200 |
| Pharmaceutical Formulations | 160 | 200 |
| **Year IV - 82.5%** |  |  |
| Pharmacotherapeutics-III | 169 | 200 |
| Hospital Pharmacy | 164 | 200 |
| Clinical Pharmacy | 173 | 200 |
| Biostatistics and Research Methodology | 81 | 100 |
| Biopharmaceutics and Pharmacokinetics | 157 | 200 |
| **Year V - 90.8%** |  |  |
| Clinical Toxicology | 83 | 100 |
| Clinical Research | 96 | 100 |
| Pharmacoepidemiology and Pharmacoeconomics | 93 | 100 |
| Clinical Pharmacokinetics & Pharmacotherapeutic Drug Monitoring | 94 | 100 |
| Clerkship | 94 | 100 |
| Project Work | 85 | 100 |
